# Generated by Django 5.1.5 on 2025-02-02 14:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_image2_products_image3_products_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
