# Generated by Django 5.1.5 on 2025-02-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(default='Slider', max_length=255),
        ),
    ]
